name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        if: success()
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          LADDER_PLUGIN_SENTRY_DSN: ${{ secrets.LADDER_PLUGIN_SENTRY_DSN }}
          LADDER_PLUGIN_LOGROCKET_ID: ${{ secrets.LADDER_PLUGIN_LOGROCKET_ID }}
          LADDER_PLUGIN_GA_ID: ${{ secrets.LADDER_PLUGIN_GA_ID }}
        run: NODE_ENV="$NODE_ENV" LADDER_PLUGIN_SENTRY_DSN="$LADDER_PLUGIN_SENTRY_DSN" LADDER_PLUGIN_LOGROCKET_ID="$LADDER_PLUGIN_LOGROCKET_ID" LADDER_PLUGIN_GA_ID="$LADDER_PLUGIN_GA_ID" yarn run build

      - name: Export
        if: success()
        run: yarn run export:next

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LADDER_GAME }}'
          channelId: live
          projectId: ladder-game
