name: GitHub Pages

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm i

      - name: Build
        if: success()
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          LADDER_PLUGIN_SENTRY_DSN: ${{ secrets.LADDER_PLUGIN_SENTRY_DSN }}
          LADDER_PLUGIN_LOGROCKET_ID: ${{ secrets.LADDER_PLUGIN_LOGROCKET_ID }}
          LADDER_PLUGIN_GA_ID: ${{ secrets.LADDER_PLUGIN_GA_ID }}
        run: NODE_ENV="$NODE_ENV" LADDER_PLUGIN_SENTRY_DSN="$LADDER_PLUGIN_SENTRY_DSN" LADDER_PLUGIN_LOGROCKET_ID="$LADDER_PLUGIN_LOGROCKET_ID" LADDER_PLUGIN_GA_ID="$LADDER_PLUGIN_GA_ID" npm run build

      - name: Export
        if: success()
        run: npm run export:next

      - name: Add No Jekyll
        if: success()
        run: touch out/.nojekyll

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: out
          commit_message: 'chore: :rocket: Deploy to GitHub pages'
          committer: divlook <uihyeon.cha@gmail.com>
          author: divlook <uihyeon.cha@gmail.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
